name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-base-docker-image-generic.yml@82f3403adc3bf4cc4fe5dbb4d8fff322b9b180ba
    with:
      dockerImage: powsybl/java
      dockerUsername: powsyblci
      eventOrganizations: gridsuite
      eventType: java_updated
    secrets:
      docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
