name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-base-docker-image-generic.yml@0d3dc19c8dc9f35281249c2e126f131a0e0d0f48
    with:
      dockerImage: powsybl/java
      dockerUsername: powsyblci
      eventOrganizations: gridsuite
      eventType: java_updated
    secrets:
      docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
