name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-base-docker-image-generic.yml@b12b907289a08b8e214be49691d0af2bb995e414
    with:
      dockerImage: powsybl/java
      dockerUsername: powsyblci
      dockerRoUsername: rogridsuiteci
      eventOrganizations: gridsuite
      eventType: java_updated
    secrets:
      docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
