name: Patch

on:
  pull_request:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: version to patch (vX.X)
        required: true

jobs:
  run-patch:
    uses: powsybl/github-ci/.github/workflows/patch-base-docker-image-generic.yml@e78e224be174768e611f1d5bb19e66312a9460fd
    with:
      githubappId: ${{ vars.POWSYBL_ACTIONS_APPID }}
      dockerImage: powsybl/java
      dockerUsername: powsyblci
      releaseVersion: ${{ github.event.inputs.releaseVersion }}
    secrets:
      githubappPrivateKey: ${{ secrets.POWSYBL_ACTIONS_SECRET }}
      docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
