name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: Release version (vX.X)
        required: true

jobs:
  run-release:
    uses: powsybl/github-ci/.github/workflows/release-base-docker-image-generic.yml@f078f32800ad0555275dedb3e200f87ad1560a83
    with:
      githubappId: ${{ vars.POWSYBL_ACTIONS_APPID }}
      dockerImage: powsybl/java
      dockerUsername: powsyblci
      releaseVersion: ${{ github.event.inputs.releaseVersion }}
    secrets:
      githubappPrivateKey: ${{ secrets.POWSYBL_ACTIONS_SECRET }}
      docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
